config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources :blogs #do
  resources :posts do #, shallow: true
    resources :comments, except: [:show]
    resources :likes
  end
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_many :posts, dependent: :destroy
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  before_action :authenticate_user!

  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  def index
    @blogs = Blog.all
  end

  def show
    #redirect_to 
  end

  def new
    @blog = Blog.new
  end


  def create
    @blog = Blog.new(blog_params)
      @blog.user_id = current_user.id
      if @blog.save
        redirect_to @blog, success: 'The blog has been created!'
      else
        render :new, danger: 'The blog has not been created!'
      end
  end

  def edit

  end

  def update
    if @blog.update_attributes(blog_params)
      redirect_to @blog, success: 'The blog has been updated!'
    else
      render :edit, danger: 'The blog has not been updated!'
    end
  end

  def destroy
    @blog.destroy
    redirect_to home_index_path, success: 'The blog has been erased!'
  end

  private

  def set_blog
      @blog = Blog.find(params[:id]) # or Blog.Blog.where(user_id: current_user.id)
  end

  def blog_params
      params.require(:blog).permit(:name)
  end


end

app/helpers/blogs_helper.rb
module BlogsHelper
 
  def user_has_blog?
    user_signed_in? and current_user.blog
  end
     
end

app/views/blogs/_blog.html.erb
<article class="blog">
  <section class="blog-head">
    <h2><%= link_to blog.name, blog_path(blog) %></h2>
    <small>
      <time><%= blog.created_at.to_date.strftime("%d %B, %Y") %></time>
      <% if owner?(blog) %>
        |
        <%= link_to 'Edit', edit_blog_path(blog) %>
        |
        <%= link_to 'Erase', blog_path(blog), method: :delete, data: {confirm: 'Are you sure?'} %>
      <% else %>
         by 
        <%= blog.user.username %> 
      <% end %>
    </small>
  </section>
</article>

app/views/blogs/_form.html.erb
<% if @blog.errors.any? %>
  <div class="alert alert-danger"> 
    <h5><%= t('common.errors') %></h5>
    <ul>
      <% @blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @blog do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit (action_name == 'new' ? 'Create' : 'Update'), class: 'btn btn-primary' %>
    <%= link_to '<< Back', :back, class: 'btn btn-outline-secondary' %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Edit Blog</h1>

<%= render 'form' %>

app/views/blogs/index.html.erb
<h1>All Existence Blogs</h1>

<%= render @blogs %>

app/views/blogs/new.html.erb
<h2>Creating Blog</h2>

<%= render 'form' %>

app/views/blogs/show.html.erb
<article class="blog">
  <section class="blog-head">
    <h1><%= @blog.name %></h1>
    <small>
      <time><%= @blog.created_at.to_date.strftime("%d %B, %Y") %></time>
      <% if owner?(@blog) %>
        |
        <%= link_to 'Edit', edit_blog_path(@blog) %>
        |
        <%= link_to 'Erase', blog_path(@blog), method: :delete, data: {confirm: 'Are you sure?'} %>
      <% end %>
    </small>
    <%= render @blog.posts %>
  </section>
    
</article>