config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources :blogs #do
  resources :posts do #, shallow: true
    resources :comments, except: [:show]
    resources :likes
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :body, presence: true, allow_blank: false
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :find_post!
  before_action :find_comment!, only: [:edit, :update]

  def index
    @comments = @post.comments.order(created_at: desc)
  end

  def new
    @comment = Comment.new(post_id: params[:post_id])
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.post_id = @post.id
    if @comment.save
      #flash[:success] = "Comment successfully added"
      redirect_to @post, success: 'The comment has been created!' #comments_path(@comment)
    else
      render :new, danger: 'The post has not been created!'
    end
  end

  def edit

  end

  def update
    if @comment.update_attributes(comment_params)
      redirect_to @post, success: 'The comment has been updated!'
    else
      render :edit, danger: 'The comment has not been updated!'
    end
  end
 
  def destroy
    @comment = @post.comments.find(params[:id])
    if @comment.user_id  == current_user.id
      @comment.destroy
      redirect_to post_path(@comment.post), success: 'The comment has been erased!'
      #redirect_to @comment.post, success: 'The comment has been erased!'
    else
      redirect_to post_path(@comment.post), danger: 'The comment has not been erased!'
    end #else
  end

  private

  def find_post!
    @post = Post.find(params[:post_id])
  end

  def find_comment!
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<article class="comment">
  <section class="comment-body">
    <%= simple_format(comment.body) %>
  </section>
  <small>
    <time><%= comment.created_at.to_date.strftime("%d %B, %Y") %></time>
    <% if owner?(comment.blog) %>
      <%= link_to 'Erase', blog_comments_path(comment), method: :delete, data: {confirm: 'Are you sure?'} %>
      <% end %>
    </small>
</article>

app/views/comments/_form.html.erb
<%= form_for [@post, @comment] do |f| %>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit 'Publish', class: 'btn btn-primary' %>
    <%= link_to '<< Back', :back, class: 'btn btn-outline-secondary' %>
  </div>
  <% f.hidden_field :post_id %>
<% end %>

app/views/comments/edit.html.erb
<h2>Edit Comment</h2>

<%= render 'form' %>

app/views/comments/new.html.erb
<h2>Creating Comment</h2>

<%= render 'form' %>