config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources :blogs #do
  resources :posts do #, shallow: true
    resources :comments, except: [:show]
    resources :likes
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :body, presence: true
  validates :blog_id, presence: true
  belongs_to :blog
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  #belongs_to :user
end

app/controllers/admin/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
      @posts = Post.all
  end

  def show
    #@post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post, success: 'The post has been created!'
    else
      render :new, danger: 'The post has not been created!'
    end
  end

  def edit
    #@post = Post.find(params[:id])
  end

  def update
    #@post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      redirect_to @post, success: 'The post has been updated!'
    else
      render :edit, danger: 'The post has not been updated!'
    end
  end

  def destroy
    #@post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path, success: 'The post has been erased!'
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  before_action :set_post, only: [:show, :edit, :update, :destroy]

  before_action :set_blog, only: [:index, :new] # :create, :index]

  def index
      #@posts = Post.where("blog_id = ?", params[:blog_id])
      #@posts = Post.all




      if params[:blog_id]
        @posts = @blog.posts
      else
        render 'root'
      end


  end

  def show
    #@post = Post.find(params[:id])
    @post.increment!(:view_count)
  end

  def new
    @post = Post.new
  end

  def create
    #@post = Blog.posts.new(post_params)
    @post = Post.new(post_params)
    @post.blog_id = current_user.blog.id #@blog.id
    if @post.save
      redirect_to @post.blog, success: 'The post has been created!'
    else
      render :new, danger: 'The post has not been created!'
    end
  end

  def edit
    #@post = Post.find(params[:id])
  end

  def update
    #@post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      redirect_to @post, success: 'The post has been updated!'
    else
      render :edit, danger: 'The post has not been updated!'
    end
  end

  def destroy
    #@post = Post.find(params[:id])
    @post.destroy
    redirect_to blog_posts_path, success: 'The post has been erased!'
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def set_blog
    @blog = Blog.find(current_user.blog.id)
  end

  def post_params
    params.require(:post).permit(:title, :body, :blog_id)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
  <div class="alert alert-danger"> 
    <h5><%= t('common.errors') %></h5>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @post do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit 'Publish', class: 'btn btn-primary' %>
    <%= link_to '<< Back', :back, class: 'btn btn-outline-secondary' %>
  </div>
  <% f.hidden_field :blog_id %>
<% end %>

app/views/posts/_post.html.erb
<article class="post">
  <section class="post-head">
    <h2><%= link_to post.title, post_path(post) %></h2>
    <small>
      <time><%= post.created_at.to_date.strftime("%d %B, %Y") %></time>
      <% if owner?(post.blog) %>
        |
        <%= link_to 'Edit', edit_post_path(post) %>
        |
        <%= link_to 'Erase', posts_path(post), method: :delete, data: {confirm: 'Are you sure?'} %>
      <% end %>
    </small>
  </section>
    
  <section class="post-body">
    <%= simple_format(post.body) %>
  </section>
  <p>
    <%= "#{post.view_count} " + 'view'.pluralize(post.view_count) %>
  </p>
  <p>
    <%= "#{post.likes.count} " + 'like'.pluralize(post.likes.count) if post.likes %>
  </p>

</article>

app/views/posts/edit.html.erb
<h1>Edit post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<%= render @posts %>

app/views/posts/new.html.erb
<h2>New post</h2>

<%= render 'form' %>

app/views/posts/show.html.erb
<!--article class="post">
  <section class="post-head"-->
    <h1><%= @post.title %></h1>
    <small>
      <time><%= @post.created_at.to_date.strftime("%d %B, %Y") %></time>
      <% if owner?(@post.blog) %>
        |
        <%= link_to 'Edit', edit_post_path(@post) %>
        |
        <%= link_to 'Erase', post_path(@post), method: :delete, data: {confirm: 'Are you sure?'} %>
      <% end %>
    </small>
  <!--/section-->
    
  <!--section class="post-body"-->
  <p>
    <%= simple_format(@post.body) %>
  </p>
  <p>
    <%= "#{@post.view_count} " + 'view'.pluralize(@post.view_count) %>
  </p>
  <p>
    <%= "#{@post.likes.count} " + 'like'.pluralize(@post.likes.count) if @post.likes %>
  </p>
  <hr>
  <% if user_signed_in? && @post.likes.find_by(user_id: current_user.id) %>
    <%= button_to 'Unlike', post_like_path(@post, @post.likes.find_by(user_id: current_user.id)), method: :delete %>
  <% else %>
    <%= button_to 'Like', post_likes_path(@post), method: :post %>
  <% end %>
  <hr>
  <%= link_to "Add Comment", new_post_comment_path(post_id: @post.id) %>
  <% if @post.comments.size != 0 %>
    <h4>Comments  (<%= @post.comments.size %>)</h4>
    
    <% @post.comments.each do |comment| %>
      <p><%= simple_format(comment.body) %></p>
        <small>
          <p>by <%= comment.user.username %> at <time><%= comment.created_at.strftime("%H:%M on %d %B, %Y") %></time>
          
          <% if owner?(comment) %>
             |
             <%= link_to 'Edit', edit_post_comment_path(@post, comment) %>
             |
            <%= link_to 'Erase', post_comment_path(@post, comment), method: :delete, data: {confirm: 'Are you sure?'} %>
          <% end %>
        </small>
      </p>
    <% end %>
    <%= link_to "Add Comment", new_post_comment_path(post_id: @post.id) %>
  <% end %>

  <!--/section>
</article-->