config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources :blogs #do
  resources :posts do #, shallow: true
    resources :comments, except: [:show]
    resources :likes
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark rounded">
        <div class="navbar-nav">
        
          <a class="nav-item nav-link" href="<%= root_path %>">Home</a>
          
          <a class="nav-item nav-link" href="<%= blogs_path %>">Blog List</a>
        
          <!-- Section for users with blogs -->

          <% if user_has_blog? %>
            <a class="nav-item nav-link" href="<%= blog_path(current_user.blog) %>">My Blog</a>
            <a class="nav-item nav-link" href="<%= new_post_path %>">Add Post</a>
          <% else %>
            <a class="nav-item nav-link" href="<%= new_blog_path %>">Create Blog</a>
          <% end %>

          <% if user_signed_in? %>
            <%= link_to "Profile", edit_user_registration_path, class: "nav-item nav-link justify-content-end" %>
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-item nav-link justify-content-end" %>
          <% else %>
            <%= link_to "Sign In", new_user_session_path, class: "nav-item nav-link justify-content-end" %>
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-item nav-link justify-content-end" %>
          <% end %>
        </div>
        <% #= link_to 'New Post', new_post_path, class: 'btn btn-outline-primary pull-xs-right' %>

        <!--ul class="navbar-nav float-right">
          <% if user_signed_in? %>
            <li class="nav-item nav-link active">
              <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
            </li>
          <% else %>
            <li class="nav-item nav-link active">
              <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
            </li>
            <li class="nav-item nav-link active">
              <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul-->

      </nav>
    
      <div class="row">
        <div class="col-md-12">
          <% flash.each do |name, message| %>
            <div class="alert <%= bootstrap_class_for(name) %>">
              <button class="close" data-dismiss="alert">&times;</button>
              <%= message %>
            </div>
          <% end %>
        </div>
      </div>
      
      <div class="row">
        <div class="col-md-12">
          <%= yield %>
        </div>
      </div>

      <div class="row">
        <div class="col-md-8 offset-md-3">
          <p class="text-primary"><%= debug(params) if Rails.env.development? %></p>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/old_application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
         <div class="navbar-nav">
           <a class="nav-item nav-link active" href="<%= root_path %>">All Posts<span class="sr-only">(current)</span></a>
           <% if user_signed_in? %>
           <a class="nav-item nav-link active" href="<%= root_path %>">My Posts<span class="sr-only">(current)</span></a>
           <% end %>
           <a class="nav-item nav-link active" href="<%= new_blog_path %>">Add Post</a>
           <a class="nav-item nav-link disabled" href="#">Disabled</a>
        </div>
        <% #= link_to 'New Post', new_post_path, class: 'btn btn-outline-primary pull-xs-right' %>

        <ul class="navbar-nav float-right">
          <% if user_signed_in? %>
            <li class="nav-item nav-link active">
              <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
            </li>
          <% else %>
            <li class="nav-item nav-link active">
              <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
            </li>
            <li class="nav-item nav-link active">
              <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>

      </nav>
    </div>
    
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <% flash.each do |name, message| %>
            <div class="alert <%= bootstrap_class_for(name) %>">
              <button class="close" data-dismiss="alert">&times;</button>
              <%= message %>
            </div>
          <% end %>
        </div>
      </div>
      <%= yield %>
    </div>
  </body>
</html>